### ISSUE TITLE
Missing Flamegraph option

### ISSUE THREAD

**Issue by kadamwhite** [Chassis/Chassis_XHGui#30]
After freshly installing and provisioning the XHGui extension, I see Call Graphs but not Flame Graphs as an option when viewing the result of a prior run. I know that flame graphs used to be an option and I don't see any change to this repo that would have removed them, so I'm curious whether this is a bug

![image](https://user-images.githubusercontent.com/442115/66599357-00dfa780-eb71-11e9-8a4a-e926c3266d3b.png)

1. What operating system do you use? 2. What version of Vagrant are you running? 3. Are you using VirtualBox or VMWare and which version are you using?
Ubuntu 19.04; Vagrant 2.2.5; vbox 6.0.10

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
```
hosts:
  - core.local

paths:
  content: content
  base: .
  wp: ../git/src # WP_PATH

synced_folders:
  ../git: /vagrant/wordpress-develop # REPO_PATH

extensions:
  - chassis/core_dev
  - chassis/xdebug
  - chassis/pretty_permalinks
  - chassis/xhprof
  - chassis/chassis_xhgui

php: 7.3
ide: VSCODE
permalink: '/%year%/%monthnum%/%postname%/'
```

5. Do you have any Chassis other extensions installed? If so, what are they?
See above
